name:                ghcid-init
version:             0.2.0
github:              "benjmhart/ghcid-init"
license:             BSD3
author:              "Ben Hart"
maintainer:          "benjmhart@gmail.com"
copyright:           "2020 Ben Hart"

default-extensions:
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveFunctor
- DeriveGeneric
- DeriveAnyClass
- DerivingStrategies
- DeriveDataTypeable
- DuplicateRecordFields
- ExplicitNamespaces
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ghcid-init#readme>

dependencies:
- base-noprelude
- cmdargs
- text
- relude
- directory
- filepath

library:
  source-dirs: src

executables:
  ghcid-init:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghcid-init

tests:
  ghcid-init-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghcid-init
